<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-06-22T16:04:59 IST" name="Default suite" finished-at="2021-06-22T16:08:42 IST" duration-ms="223740">
    <groups>
    </groups>
    <test started-at="2021-06-22T16:04:59 IST" name="Default test" finished-at="2021-06-22T16:08:42 IST" duration-ms="223740">
      <class name="DustIdTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:DustIdTest@55536d9e]" started-at="2021-06-22T16:04:59 IST" name="setUp" finished-at="2021-06-22T16:05:01 IST" duration-ms="2143" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="openPage()[pri:0, instance:DustIdTest@55536d9e]" started-at="2021-06-22T16:05:01 IST" name="openPage" finished-at="2021-06-22T16:05:25 IST" duration-ms="24141" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openPage -->
        <test-method signature="dustId()[pri:1, instance:DustIdTest@55536d9e]" started-at="2021-06-22T16:05:25 IST" name="dustId" finished-at="2021-06-22T16:08:22 IST" duration-ms="177503" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dustId -->
        <test-method signature="billingdetails()[pri:2, instance:DustIdTest@55536d9e]" started-at="2021-06-22T16:08:22 IST" name="billingdetails" finished-at="2021-06-22T16:08:33 IST" duration-ms="10865" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- billingdetails -->
        <test-method signature="shippingDetails()[pri:3, instance:DustIdTest@55536d9e]" started-at="2021-06-22T16:08:33 IST" name="shippingDetails" finished-at="2021-06-22T16:08:42 IST" duration-ms="9045" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at DustIdTest.shippingDetails(DustIdTest.java:62)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- shippingDetails -->
      </class> <!-- DustIdTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
